export const PAYLOAD_GET_EXAM = {
  sop_instance_uid: '',
  LH_btn1: true,
  LH_btn2: true,
  RH_btn1: true,
  RH_btn2: true,
  LK_btn1: true,
  LK_btn2: true,
  RK_btn1: true,
  RK_btn2: true,
  LA_btn1: true,
  LA_btn2: true,
  RA_btn1: true,
  RA_btn2: true,
};
